---- SQL CODE 1
---- THIS CODE IS TO DEMONSTRATE SQL ABILITIES OF ALBERT LEE FOR PROSPECTIVE EMPLOYERS SEEKING TO UNDERSTAND HIS SQL PROFICIENCY

-- --- BEGIN OF CONDITIONAL TEMP TABLE SET UP

-- LEADS' TOUCHPOINT LEVEL UNDERLYING DATA, WITH RANKING PER THREE LOGIC
WITH TABLE_LEADS AS (
SELECT
  LEADS.*
  ,B.BIZIBLE_TOUCHPOINT_ID
  ,B.BIZIBLE_TOUCHPOINT_LOCAL_CALENDAR_DATE
  ,B.BIZIBLE_TOUCHPOINT_LOCAL_DATEKEY
  ,B.BIZIBLE_TOUCHPOINT_LOCAL_DATETIME
  ,ROW_NUMBER() OVER(PARTITION BY B.LEAD_ID ORDER BY B.BIZIBLE_TOUCHPOINT_LOCAL_DATETIME ASC) AS FT_ORDER
  ,ROW_NUMBER() OVER(PARTITION BY B.LEAD_ID ORDER BY B.BIZIBLE_TOUCHPOINT_LOCAL_DATETIME DESC) AS LT_ORDER
  ,1 AS ET_ORDER
  ,B.BIZIBLE_SOURCE_ROLLUP
  ,B.BIZIBLE_TOUCHPOINT_POSITION_UNPARSED AS BIZIBLE_TOUCHPOINT_POSITION
  ,B.BIZIBLE_MARKETING_CHANNEL
  ,B.CHANNEL_PATH AS BIZIBLE_MARKETING_CHANNEL_PATH
  ,B.BIZIBLE_AD_CAMPAIGN_NAME
  ,B.BIZIBLE_AD_CONTENT
  ,B.BIZIBLE_FORM_URL
  ,B.CAMPAIGN_OWNER
  ,B.CAMPAIGN_TYPE
FROM 
  (
    SELECT 
      'LEAD' AS RECORD_KIND
      ,DL.LEAD_EMAIL_MASKED AS EMAIL,DL.LEAD_ID,FL.LEAD_IDKEY
      ,DL.AUTOMATIC_QUALIFIED_LEAD_DATE AS AQL_DATE
      ,FL.AUTOMATIC_QUALIFIED_DATEKEY
      ,AQL.AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER
    FROM 
      REDACTED_SCHEMA.REDACTED_TABLE_NAME DL
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME FL ON DL.LEAD_IDKEY = FL.LEAD_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME AQL ON FL.AUTOMATIC_QUALIFIED_DATEKEY = AQL.AUTOMATIC_QUALIFIED_DATEKEY
    WHERE DL.LEAD_CONVERTED_FLAG = 'FALSE'
      AND AQL.AUTOMATIC_QUALIFIED_FISCAL_YEAR >= 2023 -- ONLY REELING IN RECORDS THAT HAVE AQL THIS FISCAL YEAR 2023 IMPRINTED ON AQL DATE FIELD PER RECORD
  ) LEADS
INNER JOIN 
  (
    SELECT
      DL.LEAD_ID
      ,DL.LEAD_IDKEY
      ,DBT.BIZIBLE_TOUCHPOINT_ID
      ,BTD.BIZIBLE_TOUCHPOINT_LOCAL_CALENDAR_DATE
      ,BTD.BIZIBLE_TOUCHPOINT_LOCAL_DATEKEY
      ,DBT.BIZIBLE_TOUCHPOINT_LOCAL_DATETIME
      ,BSR.BIZIBLE_SOURCE_ROLLUP
      ,DBT.BIZIBLE_TOUCHPOINT_POSITION_UNPARSED
      --,PE.PRODUCT_ENTITY
      ,BSR.BIZIBLE_MARKETING_CHANNEL
      ,BSR.BIZIBLE_MARKETING_CHANNEL_PATH as CHANNEL_PATH
      ,DBT.BIZIBLE_AD_CAMPAIGN_NAME
      ,DBT.BIZIBLE_AD_CONTENT
      ,DBT.BIZIBLE_FORM_URL
      ,DOWN.OWNER_FULLNAME AS CAMPAIGN_OWNER
      ,DCAMP.CAMPAIGN_TYPE
    FROM
      REDACTED_SCHEMA.REDACTED_TABLE_NAME BTPE   
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME PE ON BTPE.PRODUCT_ENTITY_IDKEY = PE.PRODUCT_ENTITY_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DL ON BTPE.LEAD_IDKEY = DL.LEAD_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME BSR ON BTPE.BIZIBLE_SOURCE_ROLLUP_IDKEY = BSR.BIZIBLE_SOURCE_ROLLUP_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME TP ON BTPE.BIZIBLE_TOUCHPOINT_POSITION_IDKEY = TP.BIZIBLE_TOUCHPOINT_POSITION_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME BTD ON BTPE.BIZIBLE_TOUCHPOINT_LOCAL_DATEKEY = BTD.BIZIBLE_TOUCHPOINT_LOCAL_DATEKEY
    LEFT JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DBT ON BTPE.BIZIBLE_TOUCHPOINT_DETAIL_IDKEY = DBT.BIZIBLE_TOUCHPOINT_DETAIL_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME FCAMP ON BTPE.CAMPAIGN_IDKEY = FCAMP.CAMPAIGN_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DCAMP ON FCAMP.CAMPAIGN_IDKEY = DCAMP.CAMPAIGN_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DOWN ON FCAMP.CAMPAIGN_OWNER_IDKEY = DOWN.OWNER_IDKEY
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  ) B 
  ON LEADS.LEAD_ID = B.LEAD_ID 
  AND LEADS.LEAD_IDKEY = B.LEAD_IDKEY
  AND LEADS.AQL_DATE >= B.BIZIBLE_TOUCHPOINT_LOCAL_CALENDAR_DATE
WHERE NOT UPPER(LEADS.EMAIL) LIKE '%CISCO.COM'
ORDER BY LEAD_ID,BIZIBLE_TOUCHPOINT_LOCAL_DATETIME ASC
),


-- CONTACTS' TOUCHPOINT LEVEL UNDERLYING DATA, WITH RANKING PER THREE LOGIC
TABLE_CONTACTS AS (
SELECT
  CONTACTS.*
  ,B.BIZIBLE_TOUCHPOINT_ID
  ,B.BIZIBLE_TOUCHPOINT_LOCAL_CALENDAR_DATE
  ,B.BIZIBLE_TOUCHPOINT_LOCAL_DATEKEY
  ,B.BIZIBLE_TOUCHPOINT_LOCAL_DATETIME
  ,ROW_NUMBER() OVER(PARTITION BY B.CONTACT_ID ORDER BY B.BIZIBLE_TOUCHPOINT_LOCAL_DATETIME ASC) AS FT_ORDER
  ,ROW_NUMBER() OVER(PARTITION BY B.CONTACT_ID ORDER BY B.BIZIBLE_TOUCHPOINT_LOCAL_DATETIME DESC) AS LT_ORDER
  ,1 AS ET_ORDER
  ,B.BIZIBLE_SOURCE_ROLLUP
  ,B.BIZIBLE_TOUCHPOINT_POSITION_UNPARSED AS BIZIBLE_TOUCHPOINT_POSITION
  ,B.BIZIBLE_MARKETING_CHANNEL
  ,B.CHANNEL_PATH AS BIZIBLE_MARKETING_CHANNEL_PATH
  ,B.BIZIBLE_AD_CAMPAIGN_NAME
  ,B.BIZIBLE_AD_CONTENT
  ,B.BIZIBLE_FORM_URL
  ,B.CAMPAIGN_OWNER
  ,B.CAMPAIGN_TYPE
FROM 
  (
    SELECT 
      'CONTACT' AS RECORD_KIND
      ,PROTDC.EMAIL,PROTDC.ID AS CONTACT_ID,DC.CONTACT_IDKEY
      ,PROTDC.AUTOMATIC_QUALIFIED_DATE__C AS AQL_DATE
      ,AQL.AUTOMATIC_QUALIFIED_DATEKEY
      ,AQL.AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER
    FROM 
      REDACTED_SCHEMA.REDACTED_TABLE_NAME -- HAD TO UTILIZE TABLE FROM **REDACTED SCHEMA** INSTEAD OF **REDACTED SCHEMA** AS DW_DIM_CONTACT TABLE DOESN'T HAVE AQL DATE COLUMN
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DC ON PROTDC.ID = DC.CONTACT_ID
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME AQL ON PROTDC.AUTOMATIC_QUALIFIED_DATE__C = AQL.AUTOMATIC_QUALIFIED_CALENDAR_DATE
    WHERE AQL.AUTOMATIC_QUALIFIED_FISCAL_YEAR >= 2023
  ) CONTACTS
INNER JOIN 
  (
    SELECT
      DC.CONTACT_ID
      ,DC.CONTACT_IDKEY
      ,DBT.BIZIBLE_TOUCHPOINT_ID
      ,BTD.BIZIBLE_TOUCHPOINT_LOCAL_CALENDAR_DATE
      ,BTD.BIZIBLE_TOUCHPOINT_LOCAL_DATEKEY
      ,DBT.BIZIBLE_TOUCHPOINT_LOCAL_DATETIME
      ,BSR.BIZIBLE_SOURCE_ROLLUP
      ,DBT.BIZIBLE_TOUCHPOINT_POSITION_UNPARSED
      ,BSR.BIZIBLE_MARKETING_CHANNEL
      ,BSR.BIZIBLE_MARKETING_CHANNEL_PATH as CHANNEL_PATH
      ,DBT.BIZIBLE_AD_CAMPAIGN_NAME
      ,DBT.BIZIBLE_AD_CONTENT
      ,DBT.BIZIBLE_FORM_URL
      ,DOWN.OWNER_FULLNAME AS CAMPAIGN_OWNER
      ,DCAMP.CAMPAIGN_TYPE
    FROM
      REDACTED_SCHEMA.REDACTED_TABLE_NAME BTPE   
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME PE ON BTPE.PRODUCT_ENTITY_IDKEY = PE.PRODUCT_ENTITY_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DC ON BTPE.CONTACT_IDKEY = DC.CONTACT_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME BSR ON BTPE.BIZIBLE_SOURCE_ROLLUP_IDKEY = BSR.BIZIBLE_SOURCE_ROLLUP_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME TP ON BTPE.BIZIBLE_TOUCHPOINT_POSITION_IDKEY = TP.BIZIBLE_TOUCHPOINT_POSITION_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME BTD ON BTPE.BIZIBLE_TOUCHPOINT_LOCAL_DATEKEY = BTD.BIZIBLE_TOUCHPOINT_LOCAL_DATEKEY
    LEFT JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DBT ON BTPE.BIZIBLE_TOUCHPOINT_DETAIL_IDKEY = DBT.BIZIBLE_TOUCHPOINT_DETAIL_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME FCAMP ON BTPE.CAMPAIGN_IDKEY = FCAMP.CAMPAIGN_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DCAMP ON FCAMP.CAMPAIGN_IDKEY = DCAMP.CAMPAIGN_IDKEY
    INNER JOIN REDACTED_SCHEMA.REDACTED_TABLE_NAME DOWN ON FCAMP.CAMPAIGN_OWNER_IDKEY = DOWN.OWNER_IDKEY
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  ) B 
  ON CONTACTS.CONTACT_ID = B.CONTACT_ID 
  AND CONTACTS.CONTACT_IDKEY = B.CONTACT_IDKEY
  AND CONTACTS.AQL_DATE >= B.BIZIBLE_TOUCHPOINT_LOCAL_CALENDAR_DATE
WHERE NOT UPPER(CONTACTS.EMAIL) LIKE '%CISCO.COM'
ORDER BY CONTACT_ID,BIZIBLE_TOUCHPOINT_LOCAL_DATETIME ASC
),

-- CAMPAIGN LEVEL LEADS (UNCONVERTED ONLY) COUNTS
CAMP_UNCONV_LEAD_COUNTS AS (
SELECT 
  LEADS_ET.BIZIBLE_AD_CAMPAIGN_NAME
  ,LEADS_FT.FT_COUNT_FY23Q1
  ,LEADS_LT.LT_COUNT_FY23Q1
  ,LEADS_ET.ET_COUNT_FY23Q1
  ,LEADS_FT.FT_COUNT_FY23Q2
  ,LEADS_LT.LT_COUNT_FY23Q2
  ,LEADS_ET.ET_COUNT_FY23Q2
  ,LEADS_FT.FT_COUNT_FY23Q3
  ,LEADS_LT.LT_COUNT_FY23Q3
  ,LEADS_ET.ET_COUNT_FY23Q3
FROM 
  (
    SELECT 
      ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q3
    FROM 
      TABLE_LEADS ET_COUNT
    WHERE ET_COUNT.ET_ORDER = 1
      -- NEXT TWO LINES ONLY AIM TO GET UMBRELLA CAMPAIGNS PER ZACK MARTIN'S REQUEST TO FOCUS ON THESE FOR THIS ANALYSIS
      AND (UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
    ORDER BY 1
  ) LEADS_ET -- SET EVEN TOUCH TABLE AS THE LEFTMOST JOIN TABLE AS THIS TABLE VS. FT OR LT TABLE WOULD HAVE MUCH MORE RESULTS IN NUMBERS AND CONTENT
LEFT JOIN
  (
    SELECT 
      FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q3
    FROM 
      TABLE_LEADS FT_COUNT
    WHERE FT_COUNT.FT_ORDER = 1
      AND (UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
    ORDER BY 1
  ) LEADS_FT
  ON LEADS_ET.BIZIBLE_AD_CAMPAIGN_NAME = LEADS_FT.BIZIBLE_AD_CAMPAIGN_NAME
LEFT JOIN
  (
    SELECT 
      LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q3
    FROM 
      TABLE_LEADS LT_COUNT
    WHERE LT_COUNT.LT_ORDER = 1
      AND (UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
    ORDER BY 1
  ) LEADS_LT
  ON LEADS_ET.BIZIBLE_AD_CAMPAIGN_NAME = LEADS_LT.BIZIBLE_AD_CAMPAIGN_NAME
ORDER BY 1
),

-- CAMPAIGN LEVEL ALL CONTACTS COUNTS
CAMP_CONTACT_COUNTS AS (
SELECT 
  CONTACTS_ET.BIZIBLE_AD_CAMPAIGN_NAME
  ,CONTACTS_FT.FT_COUNT_FY23Q1
  ,CONTACTS_LT.LT_COUNT_FY23Q1
  ,CONTACTS_ET.ET_COUNT_FY23Q1
  ,CONTACTS_FT.FT_COUNT_FY23Q2
  ,CONTACTS_LT.LT_COUNT_FY23Q2
  ,CONTACTS_ET.ET_COUNT_FY23Q2
  ,CONTACTS_FT.FT_COUNT_FY23Q3
  ,CONTACTS_LT.LT_COUNT_FY23Q3
  ,CONTACTS_ET.ET_COUNT_FY23Q3
FROM 
  (
    SELECT 
      ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q3
    FROM TABLE_CONTACTS ET_COUNT
    WHERE ET_COUNT.ET_ORDER = 1
      AND (UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
  ) CONTACTS_ET
LEFT JOIN
  (
    SELECT 
      FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q3
    FROM TABLE_CONTACTS FT_COUNT
    WHERE FT_COUNT.FT_ORDER = 1
      AND (UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
  ) CONTACTS_FT
  ON CONTACTS_ET.BIZIBLE_AD_CAMPAIGN_NAME = CONTACTS_FT.BIZIBLE_AD_CAMPAIGN_NAME
LEFT JOIN
  (
    SELECT 
      LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q3
    FROM TABLE_CONTACTS LT_COUNT
    WHERE LT_COUNT.LT_ORDER = 1
      AND (UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
  ) CONTACTS_LT
  ON CONTACTS_ET.BIZIBLE_AD_CAMPAIGN_NAME = CONTACTS_LT.BIZIBLE_AD_CAMPAIGN_NAME
ORDER BY 1
),

-- CHANNEL LEVEL LEADS (UNCONVERTED ONLY) COUNTS
CHANNEL_UNCONV_LEAD_COUNTS AS (
SELECT 
  LEADS_ET.BIZIBLE_MARKETING_CHANNEL
  ,LEADS_FT.FT_COUNT_FY23Q1
  ,LEADS_LT.LT_COUNT_FY23Q1
  ,LEADS_ET.ET_COUNT_FY23Q1
  ,LEADS_FT.FT_COUNT_FY23Q2
  ,LEADS_LT.LT_COUNT_FY23Q2
  ,LEADS_ET.ET_COUNT_FY23Q2
  ,LEADS_FT.FT_COUNT_FY23Q3
  ,LEADS_LT.LT_COUNT_FY23Q3
  ,LEADS_ET.ET_COUNT_FY23Q3
FROM 
  (
    SELECT 
      ET_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q3
    FROM TABLE_LEADS ET_COUNT
    WHERE ET_COUNT.ET_ORDER = 1
      AND (UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
  ) LEADS_ET
LEFT JOIN
  (
    SELECT 
      FT_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q3
    FROM TABLE_LEADS FT_COUNT
    WHERE FT_COUNT.FT_ORDER = 1
      AND (UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
  ) LEADS_FT
  ON LEADS_ET.BIZIBLE_MARKETING_CHANNEL = LEADS_FT.BIZIBLE_MARKETING_CHANNEL
LEFT JOIN
  (
    SELECT 
      LT_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q3
    FROM TABLE_LEADS LT_COUNT
    WHERE LT_COUNT.LT_ORDER = 1
      AND (UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
    ORDER BY 1
  ) LEADS_LT
  ON LEADS_ET.BIZIBLE_MARKETING_CHANNEL = LEADS_LT.BIZIBLE_MARKETING_CHANNEL
),

-- CHANNEL LEVEL ALL CONTACTS COUNTS
CHANNEL_CONTACT_COUNTS AS (
SELECT 
  CONTACTS_ET.BIZIBLE_MARKETING_CHANNEL
  ,CONTACTS_FT.FT_COUNT_FY23Q1
  ,CONTACTS_LT.LT_COUNT_FY23Q1
  ,CONTACTS_ET.ET_COUNT_FY23Q1
  ,CONTACTS_FT.FT_COUNT_FY23Q2
  ,CONTACTS_LT.LT_COUNT_FY23Q2
  ,CONTACTS_ET.ET_COUNT_FY23Q2
  ,CONTACTS_FT.FT_COUNT_FY23Q3
  ,CONTACTS_LT.LT_COUNT_FY23Q3
  ,CONTACTS_ET.ET_COUNT_FY23Q3
FROM 
  (
    SELECT 
      ET_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q3
    FROM 
      TABLE_CONTACTS ET_COUNT
    WHERE ET_COUNT.ET_ORDER = 1
      AND (UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
  ) CONTACTS_ET
LEFT JOIN
  (
    SELECT 
      FT_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q3
    FROM 
      TABLE_CONTACTS FT_COUNT
    WHERE FT_COUNT.FT_ORDER = 1
      AND (UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
  ) CONTACTS_FT
  ON CONTACTS_ET.BIZIBLE_MARKETING_CHANNEL = CONTACTS_FT.BIZIBLE_MARKETING_CHANNEL
LEFT JOIN
  (
    SELECT 
      LT_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q3
    FROM 
      TABLE_CONTACTS LT_COUNT
    WHERE LT_COUNT.LT_ORDER = 1
      AND (UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1
  ) CONTACTS_LT
  ON CONTACTS_ET.BIZIBLE_MARKETING_CHANNEL = CONTACTS_LT.BIZIBLE_MARKETING_CHANNEL
ORDER BY 1
),

-- CHANNEL--CAMPAIGN LEVEL LEADS (UNCONVERTED ONLY) COUNTS
CHANNEL_CAMP_UNCONV_LEAD_COUNTS AS (
SELECT 
  LEADS_ET.BIZIBLE_MARKETING_CHANNEL
  ,LEADS_ET.BIZIBLE_AD_CAMPAIGN_NAME
  ,LEADS_FT.FT_COUNT_FY23Q1
  ,LEADS_LT.LT_COUNT_FY23Q1
  ,LEADS_ET.ET_COUNT_FY23Q1
  ,LEADS_FT.FT_COUNT_FY23Q2
  ,LEADS_LT.LT_COUNT_FY23Q2
  ,LEADS_ET.ET_COUNT_FY23Q2
  ,LEADS_FT.FT_COUNT_FY23Q3
  ,LEADS_LT.LT_COUNT_FY23Q3
  ,LEADS_ET.ET_COUNT_FY23Q3
FROM 
  (
    SELECT 
      ET_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q3
    FROM 
      TABLE_LEADS ET_COUNT
    WHERE ET_COUNT.ET_ORDER = 1
      AND (UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1,2
  ) LEADS_ET
LEFT JOIN
  (
    SELECT 
      FT_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q3
    FROM 
      TABLE_LEADS FT_COUNT
    WHERE FT_COUNT.FT_ORDER = 1
      AND (UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1,2
  ) LEADS_FT
  ON LEADS_ET.BIZIBLE_MARKETING_CHANNEL = LEADS_FT.BIZIBLE_MARKETING_CHANNEL 
  AND LEADS_ET.BIZIBLE_AD_CAMPAIGN_NAME = LEADS_FT.BIZIBLE_AD_CAMPAIGN_NAME
LEFT JOIN
  (
    SELECT 
      LT_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q3
    FROM 
      TABLE_LEADS LT_COUNT
    WHERE LT_COUNT.LT_ORDER = 1
      AND (UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1,2
  ) LEADS_LT
  ON LEADS_ET.BIZIBLE_MARKETING_CHANNEL = LEADS_LT.BIZIBLE_MARKETING_CHANNEL 
  AND LEADS_ET.BIZIBLE_AD_CAMPAIGN_NAME = LEADS_LT.BIZIBLE_AD_CAMPAIGN_NAME
ORDER BY 1,2
),

-- CHANNEL--CAMPAIGN LEVEL ALL CONTACTS COUNTS
CHANNEL_CAMP_CONTACT_COUNTS AS (
SELECT 
  CONTACTS_ET.BIZIBLE_MARKETING_CHANNEL
  ,CONTACTS_ET.BIZIBLE_AD_CAMPAIGN_NAME
  ,CONTACTS_FT.FT_COUNT_FY23Q1
  ,CONTACTS_LT.LT_COUNT_FY23Q1
  ,CONTACTS_ET.ET_COUNT_FY23Q1
  ,CONTACTS_FT.FT_COUNT_FY23Q2
  ,CONTACTS_LT.LT_COUNT_FY23Q2
  ,CONTACTS_ET.ET_COUNT_FY23Q2
  ,CONTACTS_FT.FT_COUNT_FY23Q3
  ,CONTACTS_LT.LT_COUNT_FY23Q3
  ,CONTACTS_ET.ET_COUNT_FY23Q3
FROM 
  (
    SELECT 
      ET_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS ET_COUNT_FY23Q3
    FROM 
      TABLE_CONTACTS ET_COUNT
    WHERE ET_COUNT.ET_ORDER = 1
      AND (UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(ET_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1,2
  ) CONTACTS_ET
LEFT JOIN
  (
    SELECT 
      FT_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS FT_COUNT_FY23Q3
    FROM 
      TABLE_CONTACTS FT_COUNT
    WHERE FT_COUNT.FT_ORDER = 1
      AND (UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(FT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1,2
  ) CONTACTS_FT
  ON CONTACTS_ET.BIZIBLE_MARKETING_CHANNEL = CONTACTS_FT.BIZIBLE_MARKETING_CHANNEL 
  AND CONTACTS_ET.BIZIBLE_AD_CAMPAIGN_NAME = CONTACTS_FT.BIZIBLE_AD_CAMPAIGN_NAME
LEFT JOIN
  (
    SELECT 
      LT_COUNT.BIZIBLE_MARKETING_CHANNEL
      ,LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q1' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q1
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q2' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q2
      ,COUNT(DISTINCT CASE WHEN AUTOMATIC_QUALIFIED_FISCAL_YEAR_QUARTER = '2023/Q3' THEN EMAIL ELSE NULL END) AS LT_COUNT_FY23Q3
    FROM TABLE_CONTACTS LT_COUNT
    WHERE LT_COUNT.LT_ORDER = 1
      AND (UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%FY23-%' OR UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE '%UMB_23%') 
      AND UPPER(LT_COUNT.BIZIBLE_AD_CAMPAIGN_NAME) LIKE 'UMB%'
    GROUP BY 1,2
  ) CONTACTS_LT
  ON CONTACTS_ET.BIZIBLE_MARKETING_CHANNEL = CONTACTS_LT.BIZIBLE_MARKETING_CHANNEL 
  AND CONTACTS_ET.BIZIBLE_AD_CAMPAIGN_NAME = CONTACTS_LT.BIZIBLE_AD_CAMPAIGN_NAME
ORDER BY 1
)

-- -- END OF CONDITIONAL TEMP TABLE SET UP


-- QUERIES TO BASE-CHECK DATA
--SELECT * FROM TABLE_LEADS WHERE LEAD_ID LIKE '00Q1T00001MW62fUAD%'
--SELECT TOP 100 * FROM CHANNEL_CAMP_UNCONV_LEAD_COUNTS

-- CAMPAIGN LEVEL, UNCONVERTED LEADS + CONTACT RECORDS TOTAL
--SELECT 
--  BIZIBLE_AD_CAMPAIGN_NAME
--  ,SUM(FT_COUNT_FY23Q1) AS FY23Q1_FT
--  ,SUM(LT_COUNT_FY23Q1) AS FY23Q1_LT
--  ,SUM(ET_COUNT_FY23Q1) AS FY23Q1_ET
--  ,SUM(FT_COUNT_FY23Q2) AS FY23Q2_FT
--  ,SUM(LT_COUNT_FY23Q2) AS FY23Q2_LT
--  ,SUM(ET_COUNT_FY23Q2) AS FY23Q2_ET
--  ,SUM(FT_COUNT_FY23Q3) AS FY23Q3_FT
--  ,SUM(LT_COUNT_FY23Q3) AS FY23Q3_LT
--  ,SUM(ET_COUNT_FY23Q3) AS FY23Q3_ET
--  ,SUM(FT_COUNT_FY23Q1)+SUM(FT_COUNT_FY23Q2)+SUM(FT_COUNT_FY23Q3) AS FY23_FT
--  ,SUM(LT_COUNT_FY23Q1)+SUM(LT_COUNT_FY23Q2)+SUM(LT_COUNT_FY23Q3) AS FY23_LT
--  ,SUM(ET_COUNT_FY23Q1)+SUM(ET_COUNT_FY23Q2)+SUM(ET_COUNT_FY23Q3) AS FY23_ET
--  ,CAST(((FY23_ET/FY23_LT-1.00)*100.00) AS NUMBER(20,1))||'%' AS DIFFERENCE_LT_VS_ET_FY23
--FROM
--  (SELECT * FROM CAMP_UNCONV_LEAD_COUNTS UNION ALL SELECT * FROM CAMP_CONTACT_COUNTS)
--GROUP BY 1
--ORDER BY 1

-- CHANNEL LEVEL, UNCONVERTED LEADS + CONTACT RECORDS TOTAL
SELECT 
  BIZIBLE_MARKETING_CHANNEL
  ,BIZIBLE_AD_CAMPAIGN_NAME
--  ,SUM(FT_COUNT_FY23Q1) AS FY23Q1_FT
--  ,SUM(LT_COUNT_FY23Q1) AS FY23Q1_LT
--  ,SUM(ET_COUNT_FY23Q1) AS FY23Q1_ET
--  ,SUM(FT_COUNT_FY23Q2) AS FY23Q2_FT
--  ,SUM(LT_COUNT_FY23Q2) AS FY23Q2_LT
--  ,SUM(ET_COUNT_FY23Q2) AS FY23Q2_ET
--  ,SUM(FT_COUNT_FY23Q3) AS FY23Q3_FT
--  ,SUM(LT_COUNT_FY23Q3) AS FY23Q3_LT
--  ,SUM(ET_COUNT_FY23Q3) AS FY23Q3_ET
  ,SUM(FT_COUNT_FY23Q1)+SUM(FT_COUNT_FY23Q2)+SUM(FT_COUNT_FY23Q3) AS FY23_FT
  ,SUM(LT_COUNT_FY23Q1)+SUM(LT_COUNT_FY23Q2)+SUM(LT_COUNT_FY23Q3) AS FY23_LT
  ,SUM(ET_COUNT_FY23Q1)+SUM(ET_COUNT_FY23Q2)+SUM(ET_COUNT_FY23Q3) AS FY23_ET
  ,CAST(((FY23_ET/FY23_LT-1.00)*100.00) AS NUMBER(20,1))||'%' AS DIFFERENCE_LT_VS_ET_FY23
FROM
  (SELECT * FROM CHANNEL_CAMP_UNCONV_LEAD_COUNTS UNION ALL SELECT * FROM CHANNEL_CAMP_CONTACT_COUNTS)
GROUP BY 1,2
ORDER BY 1,2
